### ISSUE TITLE
Incompatible with Psalm 3.7?

### ISSUE THREAD

**Issue by unlikenesses** [psalm/laravel-psalm-plugin#17]
I have Psalm 3.7 installed. When I run

`composer require --dev psalm/plugin-laravel`

Composer tells me:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for psalm/plugin-laravel ^0.7.0 -> satisfiable by psalm/plugin-laravel[0.7].
>     - psalm/plugin-laravel 0.7 requires vimeo/psalm 3.2.*|3.3.*|3.4.*|3.5.*|3.6.* -> satisfiable by vimeo/psalm[3.2, 3.2.10, 3.2.11, 3.2.12, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.10, 3.4.11, 3.4.12, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.6.5, 3.6.6] but these conflict with your requirements or minimum-stability.

**Comment by muglug** [comment]
Sorry, I've just pushed a new release that is compatible
